Пономарев Степан - АВЛ Деревце
polis-mail-ru/2020-ads pull request #157
Opened 2020-11-06 17:19 UTC by step-ponomarev

2020-11-07 12:58 UTC, dormidon commented on src/test/java/ru/mail/polis/ads/bst/BstBaseTest.java
> -    Bst<String, String> newBst() {
А что тут поменялось?
Если только форматирование, то нужно откатить эти изменения.

2020-11-08 12:24 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/bst/AvlBst.java
> +    if (avl == null) {
А если оно не null, то разве не нужно обновлять ссылку на корень на новое дерево?

2020-11-08 12:25 UTC, dormidon requested changes
См. комменты.

2020-11-09 15:06 UTC, step-ponomarev commented on src/test/java/ru/mail/polis/ads/bst/BstBaseTest.java
> -    Bst<String, String> newBst() {
Я там кажись пустую строку убирал.
Скопировал тесты из ветки `avl` и просто вставил, не стал откатывать изменения. Можно?

2020-11-09 15:06 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/ads/bst/AvlBst.java
> +    if (avl == null) {
да, верно.

2020-11-11 20:13 UTC, dormidon approved these changes

2020-11-11 20:14 UTC, closed without merging