Homework6 (avl)
polis-mail-ru/2020-ads pull request #158
Opened 2020-11-07 15:48 UTC by romanmarasanov

Пока работают только два простейших теста, хотя есть другие довольно простые тесты (например, contains()), которые сваливаются после первой же вставки и проверки наличия по ключу. Перепроверил много раз get() и put(), пока оставляю так. Может, вы увидите ошибку :)

2020-11-08 12:17 UTC, dormidon commented
Я-то, может быть, и увижу (точнее, уже увидел), но было бы здорово, чтобы вы сами докопались до проблемы.
Возможно, стоит подебажить и посмотреть на состояние объекта после вставки элемента.

2020-11-09 13:48 UTC, romanmarasanov commented
Всё понял и осознал))

2020-11-11 20:15 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/bst/AvlBst.java
> +        if (key.compareTo(x.key) < 0) x.left = put(x.left, key, value);
Мы дважды выполняем операцию сравнения
`key.compareTo(x.key)`
В реальных ситуациях эта операция может быть дорогой, и лучше ее выполнить один раз.

2020-11-11 20:15 UTC, dormidon requested changes
Нужно убрать повторные key.compareTo(x.key)

2020-11-13 14:32 UTC, dormidon approved these changes

2020-11-13 14:32 UTC, closed without merging