Saveliy Schur - Part6
polis-mail-ru/2020-ads pull request #178
Opened 2020-11-10 10:35 UTC by SaveliyShur

2020-11-11 20:30 UTC, dormidon requested changes
Убрать повторяющиеся сравнения.

2020-11-12 13:37 UTC, SaveliyShur commented
Готово

2020-11-15 14:40 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/bst/AvlBst.java
> +        if(key.compareTo(node.key) < 0) return getValue(node.left, key);
Вот ведь еще повторное сравнение.

2020-11-15 14:40 UTC, dormidon requested changes
Не всё убрано.

2020-11-15 22:44 UTC, SaveliyShur commented on src/main/java/ru/mail/polis/ads/bst/AvlBst.java
> +        if(key.compareTo(node.key) < 0) return getValue(node.left, key);
А разве сравнение ссылок будет сильно влиять?

2020-11-20 16:17 UTC, dormidon approved these changes

2020-11-20 16:17 UTC, closed without merging