add 6 hw: Peutina Veronika
polis-mail-ru/2020-ads pull request #187
Opened 2020-11-11 16:29 UTC by NickPeut

2020-11-11 16:31 UTC, NickPeut commented
Я не знаю, как это исправить, я не смогла зачекаутить вашу ветку, создала свою с такими же файлами.

2020-11-11 16:32 UTC, NickPeut commented
Потестила руками на тестах из файла BstBaseTest.java
там все тесты "passed"

2020-11-11 20:36 UTC, dormidon requested changes
Убрать повторяющиеся сравнения.

2020-11-20 16:19 UTC, dormidon approved these changes

2020-11-20 16:19 UTC, closed without merging