Red/Black(I am BLM, and im not a racist) GromovMaxim
polis-mail-ru/2020-ads pull request #203
Opened 2020-11-16 23:15 UTC by Maxim-byte

2020-11-20 16:35 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/bst/RedBlackBst.java
> +            if(node.key.compareTo(key) > 0 && node.left != null) {
Таки повторяющиеся сравнения. 
Надо выпилить.

2020-11-20 16:35 UTC, dormidon requested changes
Повторяющиеся сравнения.

2020-11-20 21:17 UTC, Maxim-byte commented
@dormidon, исправил

2020-11-22 16:29 UTC, dormidon approved these changes

2020-11-22 16:29 UTC, closed without merging