Solved hw8 | Sakhibgareev Ramis
polis-mail-ru/2020-ads pull request #218
Opened 2020-11-20 19:06 UTC by rapturemain

2020-11-22 16:35 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/HashTableImpl.java
> +    private Object[] hashTable;
Тут можно без приведения типов `Bucket[] hashTable`.

2020-11-22 16:36 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/HashTableImpl.java
> +        Object[] bucket;
Здесь, кажется, можно использовать `Entry[] bucket`. Поскольку наш `private class Bucket` не `static`, то он может знать про параметры типа `Entry`.

2020-11-22 16:39 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/HashTableImpl.java
> +            return key.hashCode() * 31 + value.hashCode();
В нашем случае при поиске по Entry мы сравниваем ключи (что явно отражено в `equals`). А здесь в `hashCode` мы еще учитываем значение.
Тем самым оно и не корректно с точки зрения поведения структуры данных, так и с точки зрения согласованности: если у нас entry будут equals(), то не факт, что их hashCode() совпадет.

2020-11-22 16:40 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/HashTableImpl.java
> +        static final int EXISTED = 1;
Кажется, тут можно обойтись просто `true/false`.
Многие библиотечные структуры данных так и делают. 
Например, тот же базовый `Collection.add` возвращает `true`, если элемент действительно добавился и коллекция изменилась, и `false` иначе.

2020-11-22 16:41 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/HashTableImpl.java
> +        int getEntryIndex(@NotNull K k) {
Дублирование кода с `getEntry`.

2020-11-22 16:57 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/HashTableImpl.java
> +    private boolean resize(int newSize, int newBucketSize) {
Я не очень понимаю смысла варьирования длины цепочки, в этой реализации - длины массива, `newBucketSize`.
Идея разрешения коллизий методом цепочек в том, чтобы держать цепочки как можно меньшей длины - 1 значение или изредка 2 в случае коллизии. Все это для того, чтобы получить O(1) на основных операциях.
И сдерживать рост длины цепочек мы можем как раз за счет изменения размеров основного массива - делаем его больше, цепочки становятся короче.
В таком случае эти цепочки удобнее организовывать в виде связного списка
1. Накладные расходы практически не отличаются для связного списка из одного или двух элементов от массива.
2. Массив еще и занимает какую-то память, даже если в нем ничего не хранится
3. Реализовывать ресайз нужно лишь по одному "измерению" - основному массиву, где мы храним "головы" наших связных списков.

2020-11-22 16:58 UTC, dormidon requested changes
1. Явные замечания по коду
2. Не очень понятна мотивация хранить цепочки в массиве. Отписал комментом к resize(). Нужно либо обосновать такой выбор, либо сделать на связных списках (что в значительной мере и код упростит).

2020-11-24 16:59 UTC, rapturemain commented on src/main/java/ru/mail/polis/ads/hash/HashTableImpl.java
> +            return key.hashCode() * 31 + value.hashCode();
Такая реализация осталась после использования коллекций, было лень проходиться по ним ручками, чтобы найти нужный Entry)
Про соглашения между equals() и hashCode() забыл, к сожалению

2020-11-28 14:29 UTC, dormidon commented
В ветке в основном репозитории появились новые тесты, нужно их подтянуть.

2020-11-28 14:37 UTC, rapturemain commented
Через rebase?

On Sat, 28 Nov 2020, 17:29 Dmitry Schitinin, <notifications@github.com>
wrote:

> В ветке в основном репозитории появились новые тесты, нужно их подтянуть.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/polis-mail-ru/2020-ads/pull/218#issuecomment-735237607>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKIRD3SNTWOFOH3LSHHLZCTSSECMVANCNFSM4T5EVYIQ>
> .
>

2020-11-28 15:28 UTC, dormidon commented
Как удобно. Можно через rebase, можно через merge.
https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

2020-11-29 23:38 UTC, rapturemain commented
Что-то я с rebase накосячил, но пойдет, наверное

2020-11-30 07:52 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/HashTableImpl.java
> +        return (usingIdentityHashCode ? System.identityHashCode(key) : key.hashCode()) & (tableSize - 1);
Не очень понятно, для чего нам здесь использовать identityHashCode?
Ну стала у нас основная таблица большая, упёрлась в Int.MAX_VALUE, а чем нам здесь identityHashCode сделает жизнь лучше?

2020-11-30 07:58 UTC, rapturemain commented on src/main/java/ru/mail/polis/ads/hash/HashTableImpl.java
> +        return (usingIdentityHashCode ? System.identityHashCode(key) : key.hashCode()) & (tableSize - 1);
Чтобы добиться более равномерного распределения в случае очень плохой хэш функции. Хотя реализовывание перехода на identityHashCode() в методе resize ошибкой было, как я сейчас понимаю. Вернее было бы добавить это в put методе, если, например, размер bucket больше четверти (или даже что-то меньше четверти взять) size таблицы

2020-11-30 08:02 UTC, rapturemain commented on src/main/java/ru/mail/polis/ads/hash/HashTableImpl.java
> +        return (usingIdentityHashCode ? System.identityHashCode(key) : key.hashCode()) & (tableSize - 1);
Как-нибудь так, например
```
@Override
    public void put(@NotNull K k, @NotNull V v) {
        if (size > threshold) {
            resize();
        }

        int index = hashCode(k);
        Entry<K, V> entry = hashTable[index];

        // Empty bucket check
        if (entry == null) {
            hashTable[index] = new Entry<>(k, v);
            size++;
            return;
        }
        if (entry.key.equals(k)) {
            entry.value = v;
            return;
        }

        // Find entry in bucket and replace/add new value
        int bucketSize = 0;
        boolean cmp = false;
        while (entry.next != null && !(cmp = entry.next.key.equals(k))) {
            entry = entry.next;
            bucketSize++;
        }
        if (cmp) {
            entry.next.value = v;
        } else {
            entry.next = new Entry<>(k ,v);
            size++;
            if (bucketSize > MIN_BUCKET_SIZE_IDENTITY (пусть будет 10) && bucketSize > size / 4) {
                usingIdentityHashCode = true;
                resize();
            }
        }
    }
```

2020-11-30 16:26 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/HashTableImpl.java
> +        return (usingIdentityHashCode ? System.identityHashCode(key) : key.hashCode()) & (tableSize - 1);
Спасибо, так стало понятнее, да.
Только работать оно корректно не будет. 
Представьте в качестве ключа класс
```
class Person {
  final String name;
  final String surname;

  int hashCode() {
    return hash(name, surname);
  }
```

Теперь сначала, что когда таблица маленькая, мы добавляем элементы по таким ключам, используя в качестве hashCode какую-то комбинацию имени и фамилии. Надобавляли до предела, сработала логика на переделывание на identityHashCode(). Потом мы придем с каким-нибудь конкретным инстансом `Person`, возьмем от него identityHashCode() и ничего не найдем.
Дело в том, что всегда верно
```
(new Person("foo", "bar")).hashCode == (new Person("foo", "bar").hashCode())
```

А вот это НЕ верно
```
System.identityHashCode(new Person("foo", "bar")) == System.identityHashCode(new Person("foo", "bar"))
```
Ибо в качестве identityHashCode без дополнительных ключиков JVM берется случайное значение.

Вы можете сами убедиться, что работать ничего не будет, если запустите тесты на версии кода, когда просто используется identityHashCode(). Если бы все было так просто и оно без проблем работало на identityHashCode(), то нам вообще не нужно было бы переопределять hashCode() :)

![image](https://user-images.githubusercontent.com/727478/100635721-e6065e80-3341-11eb-872f-97e182f5f4ae.png)

2020-11-30 16:27 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/HashTableImpl.java
> +        return (usingIdentityHashCode ? System.identityHashCode(key) : key.hashCode()) & (tableSize - 1);
Текущие тесты проходят оттого, что этот порог перехода к System.identityHashCode() не достигается.

2020-11-30 16:27 UTC, dormidon requested changes
См. коммент.

2020-12-01 15:19 UTC, rapturemain commented on src/main/java/ru/mail/polis/ads/hash/HashTableImpl.java
> +        return (usingIdentityHashCode ? System.identityHashCode(key) : key.hashCode()) & (tableSize - 1);
Все понял, спасибо, что подробно объяснили
Не учел, что главная задача таблицы - поиск значения по ключу перестанет выполняться, думал только про хранение вхождений в бакетах поменьше

2020-12-05 14:29 UTC, dormidon approved these changes

2020-12-05 14:30 UTC, closed without merging