Krivitskii Vadim - Hash Table
polis-mail-ru/2020-ads pull request #221
Opened 2020-11-20 23:03 UTC by OGSegu

2020-11-20 23:04 UTC, OGSegu commented
Я не знаю почему тесты в пулл реквесте не работают, мне уже очень любопытно. Выкладываю скриншот, что тесты прошли.
![image](https://user-images.githubusercontent.com/51200522/99858151-f37f5400-2b9d-11eb-8042-02c3ef4d4722.png)

2020-11-22 17:04 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/HashMapNode.java
> +        String[] oldArray = array.clone();
А для чего clone()?
Нам ведь просто достаточно запомнить ссылку на старый массив, чтобы потом по нему пробежаться.
Копировать все не имеет смысле. Более того, элемент массива может быть не `Clonable`.

2020-11-22 17:05 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/HashMapNode.java
> +public class HashMapNode implements HashTable<String, String> {
Можно вместо явного `String` в качестве параметра типа использовать `Key` и `Value`, написав

```
public class HashMapNode<Key, Value> implements HashTable<Key, Value>
```

Мы ведь стараемся сделать структуру "общего назначения", а не которая умеет только строки.
Не будем же мы для других классов делать такую же реализацию.

2020-11-22 17:06 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/HashMapNode.java
> +        return Objects.hashCode(key) % array.length;
Чудо, что у нас небольшие строки и на них получается небольшой неотрицательный hashCode().
Если hashCode() будет отрицательным, то мы получим где-нибудь `ArrayIndexOutOfBoundException`.

2020-11-22 17:07 UTC, dormidon requested changes
1. Комменты по коду
2. String заменить на параметры типов

2020-11-24 15:53 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/HashMapNode.java
> +public class HashMapNode<Key extends Comparable<Key>, Value> implements HashTable<Key, Value> {
У нас ведь для HashTable не требуется, чтобы ключи были Comparable - в этом одно из преимуществ такой схемы.

2020-11-24 15:54 UTC, dormidon requested changes
Нужно допилить, чтобы работа происходила с не-Comparable ключами.

Дерево поиска можно использовать как оптимизацию в ряде случаев. В штатной ситуации и так все должно хорошо работать - на связных списках, которые в штатной ситуации совсем короткие (1-2 элемента).

2020-11-24 17:02 UTC, OGSegu commented
Исправил

2020-11-24 17:17 UTC, OGSegu commented
Исправил

2020-11-24 17:17 UTC, dormidon commented
И оно реально работает?
Там ведь под капотом в итоге идет сравнение объектов по System.identityHashcode().
Нужно запустить обновленные тесты - скорее всего, что-то сломается.

2020-11-24 17:18 UTC, OGSegu commented
> 
> 
> И оно реально работает?
> Там ведь под капотом в итоге идет сравнение объектов по System.identityHashcode().
> Нужно запустить обновленные тесты - скорее всего, что-то сломается.

Посмотрите обновленное. Я подправил. Тесты проходят

2020-11-24 17:34 UTC, dormidon commented
Оно чудом работает, ибо String реализует Comparable. 
Сейчас докину тест, где объект не Comparable, тогда почти наверняка сломается.

2020-11-24 17:58 UTC, dormidon commented
Добавил тесты в upstream.
Подтягивайте ветку, проверяйте.

2020-11-24 18:13 UTC, OGSegu commented
![image](https://user-images.githubusercontent.com/51200522/100134402-36d90b80-2e99-11eb-88cd-50c8deeda35f.png)

У меня все работает. Я просто не понял, почему оно может не работать, жалко тестов у меня встроенных в пулл реквест нет.

2020-11-24 18:26 UTC, dormidon commented
Оно может не работать, ибо мы объекты сравниваем по IdentityHashCode.
В тестах оно работало, потому что там переиспользовались объекты.
Чуть подправил тесты, обновляйтесь :)

2020-11-24 19:07 UTC, OGSegu commented
> Оно может не работать, ибо мы объекты сравниваем по IdentityHashCode.
> В тестах оно работало, потому что там переиспользовались объекты.
> Чуть подправил тесты, обновляйтесь :)

Щас не заработало да, все, понял в чем причина. Спасибо, за наглядный пример)
Но по факту просто замена indentityHashCode -> hashcode(), фиксит это, да?

2020-11-24 19:43 UTC, OGSegu commented
![image](https://user-images.githubusercontent.com/51200522/100143437-63dfeb00-2ea6-11eb-9006-da41fd9da519.png)
Вот так вроде работает все

2020-11-24 20:17 UTC, dormidon commented
Да, здорово, что нашли ошибку 👍 

Только мы все равно не в то направление немного ушли. 
Если посмотреть на получившееся решение, то можно увидеть некоторую избыточность и переусложненность
  1. Имея текущую реализацию Bst, которая может работать и не с Comparable ключами, встает вопрос, зачем нам вообще HashTable
  2. Реализация красно-чёрного дерева сама по себе не очень тривиальная (и занимает большую часть кода решения, превосходя основную часть задания - хеш-табличку)
  3. В нормальной ситуации, когда у нас хэш-функция хорошая (т.е. у наших ключей .hashCode() хороший), и когда мы вовремя делаем resize, то коллизии возникают редко - следовательно, цепочки короткие - 1-2 элемента. В текущем решении на месте этих цепочек висит дерево из одного узла, изредка из двух. Поиск в этом дереве, соответственно, происходит за 1-2 сравнения, то же самое, что в списке из 1-2 элементов. 

"Математически" все верно и даже "красиво" - мы свели задачу к той, которую умеем решать, но с точки зрения software engineering решение переусложнено. Практическая задача состояла в том, чтобы попробовать написать "классическую" простую хеш-табличку, без использования дополнительных структур данных. Т.е. вместо дерева подвесить ad-hoc связный список, состоящий из узлов вида
```
class Node {
  Key key;
  Value value;
  Node next;
}
```
и при появлении коллизии итерироваться по такому списку. 

Применение более сложной структуры, типа дерева, оправдана как оптимизация (а не как основной случай), когда hashCode ведет себя "плохо" (например, возвращает константу), тогда получается немного цепочек, но очень длинных. И чтобы ускорить в них последовательный поиск, этот список организуют в дерево со всеми этими хаками с Comparable и сравнением по identityHashCode(). 

И с точки зрения производительности мы тоже привносим избыточные операции, от которых свободна "классическая" реализация, например, instanceOf, compareTo, compare by identityHashCode. Добавление этих операций оправдано, когда происходит оптимизация длинных цепочек - мы меняем k вызовов equals на списке на log(k) instanceOf/compare. Если же у нас цепочки короткие (единицы элементов), то это усложнение с деревом снижает производительность.

2020-11-24 20:27 UTC, OGSegu commented
Мне просто решение со связанным списком показалось несколько тривиальным и поэтому решил сделать что-то более сложное, интересное и, как я думал, более эффективное (как то не задумывался, что рехэш позволит особо в деревьях не нуждаться), но по итогу перемудрил получается. Ну ладно, мне в принципе в "исследовательских" целях была интересна такая реализация. А она будет засчитана или переделывать под Node ?

2020-11-24 20:35 UTC, dormidon commented
Да, всё так. 
Очень здорово, что в решении такой элемент самостоятельности (к сожалению, редко встречается), и это надо обязательно поощрить.
В текущем решении не очень оптимально работает основной случай, но реализована хорошая нетривиальная оптимизация для некоторых граничных случаев, и это не надо терять.
Я предлагаю допилить так, что связный список превращается в дерево, только если он становится длиннее определенного порога (даже без обратного превращение с список при уменьшении числа элементов). Таким образом, и основная задача будет решена в полном объёме, и хорошая оптимизация для граничных случаев. При этом будет 10 баллов за основное задание и 5 дополнительных.

2020-11-24 20:38 UTC, OGSegu commented
Да, хорошо, попробую сделать

2020-11-26 21:42 UTC, OGSegu commented
Готово. 
![image](https://user-images.githubusercontent.com/51200522/100392983-64fd4d80-3049-11eb-8867-64ad0e6b9b17.png)

2020-11-28 14:32 UTC, dormidon approved these changes
👍 
10 за основное + 5 за оптимизацию деревом.

2020-11-28 14:33 UTC, closed without merging