Homework 8 - Timofey Pletnev
polis-mail-ru/2020-ads pull request #224
Opened 2020-11-21 17:51 UTC by TiMaTiFeY

HashTable realisation

2020-11-22 17:14 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/Table.java
> +public class Table<Key extends Comparable<Key>, Value>
В случае хеш-таблиц нам не обязательно иметь `Comparable` ключ, что иногда может быть преимуществом.

2020-11-22 17:16 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/Table.java
> +    private static class Cell<Key extends Comparable<Key>, Value> {
Можно убрать `static`, тогда параметры типов внешнего класса будут "видны" тут, а локальные параметры типа можно выпилить, тем самым "облегчив" все сигнатуры.

2020-11-22 17:16 UTC, dormidon requested changes
См. комменты.

2020-11-22 18:34 UTC, TiMaTiFeY commented on src/main/java/ru/mail/polis/ads/hash/Table.java
> +    private static class Cell<Key extends Comparable<Key>, Value> {
Тогда будет нельзя создать массив `Cell[]` - из-за `Generic array creation`. Только если не делать танец с бубном в виде:
` @SuppressWarnings("unchecked")
    private Cell[] table = (Cell[]) new Object[capacity];`
И то, при компиляции бросается исключение `java.lang.ClassCastException`

2020-11-24 15:58 UTC, dormidon approved these changes

2020-11-24 15:58 UTC, closed without merging