saakyan sergey \\ hash tables
polis-mail-ru/2020-ads pull request #227
Opened 2020-11-22 01:19 UTC by ogaMoga

2020-11-22 17:19 UTC, dormidon commented on MyTable.java
> +    private class Elem<Key, Value> {
Поскольку вложенный класс не `static`, то он может "видеть" и "использовать" параметры типа внешнего класса. Другими словами, дженерики тут можно безболезненно выпилить, а станет даже лучше.

2020-11-22 17:20 UTC, dormidon commented on MyTable.java
> +    private Elem[] array = new Elem[16];
Мне кажется, что лучше этот размер передавать в конструкторе + завести конструктор по-умолчанию, который будет использовать конкретное значение.

2020-11-22 17:21 UTC, dormidon requested changes
См. комменты. 
Плюс почему-то в PR две реализации (отличаются, похоже, лишь пакетами).
И нерелевантные изменения в других файлах, которые нужно убрать из PR.

2020-11-22 22:00 UTC, ogaMoga commented
Не могу убрать HashTables.java, т.к. почему-то перестаёт собираться Travis CI :(

2020-11-24 16:00 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/MyTable.java
> +        while ( (current.nextElem != null) && (current.key != key) ) {
Здесь и в других метода `!=` нужно заменить на `equals`. `!=` - это ссылочное неравенствнво. 
Тут чудо, что тесты на строковых литералах, поэтому они ссылочно равны. А так бы ничего не работало.

2020-11-24 16:00 UTC, dormidon requested changes
Использовать `equals`.

2020-11-24 19:27 UTC, closed without merging