Implementation of HashTable | Gulyaev Anton
polis-mail-ru/2020-ads pull request #228
Opened 2020-11-22 18:08 UTC by kish-dev

2020-11-24 16:01 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/Table.java
> +        int size = 0;
А нужны ли нам тут `size` и `tail`?

2020-11-24 16:01 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/Table.java
> +            if (tail != null && tail.key == key) {
Используем `==` для проверки равенства объектов - нужно `equals`.

2020-11-24 16:02 UTC, dormidon requested changes
1. Убрать избыточную реализацию списка (ненужные поля и методы)
2. Перейти на `equals()`.

2020-11-24 17:35 UTC, kish-dev commented on src/main/java/ru/mail/polis/ads/hash/Table.java
> +        int size = 0;
ну так я добавляю в конец за константу, могу, например, добавлять в начало, не знаю, как это будет

2020-11-24 18:02 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/Table.java
> +        int size = 0;
А для чего нам в данной задаче добавлять в конец?
При добавлении нам ведь все равно нужно пробежаться по всему списку, дабы понять, нет ли уже ключа, по которому мы добавляем. И если есть - то заменить значение.

2020-11-26 14:48 UTC, kish-dev commented on src/main/java/ru/mail/polis/ads/hash/Table.java
> +        int size = 0;
Окей, согласен

2020-11-28 14:35 UTC, dormidon approved these changes

2020-11-28 14:35 UTC, closed without merging