HW8 | Shabinsky Dmitry
polis-mail-ru/2020-ads pull request #234
Opened 2020-11-23 20:15 UTC by sdimosik

2020-11-28 14:51 UTC, dormidon requested changes
Решение черезчур подозрительно похоже на https://github.com/polis-mail-ru/2020-ads/pull/231 - вот с точностью до переименования констант и класса. 
Понятно, что текущая задача - не простор для творчества, но настолько близкие решения встречаю впервые. Можете как-то это объяснить?

2020-11-28 15:46 UTC, sdimosik commented
@dormidon Из-за нехватки времени я чекнул решение #231 . В течении дня предоставлю своё решение

2020-11-30 07:54 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/Hash.java
> +                    values.set(pos, value);
И какая у нас здесь сложность выставления значения элемента по индексу?

2020-11-30 07:54 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/Hash.java
> +                    return values.remove(pos);
Какая здесь сложность удаления элемента по индексу?

2020-12-01 15:34 UTC, sdimosik commented
Извиняюсь за задержку ответа, просто почему-то мои комментарии не отправились сразу, а оказались в проверке

2020-12-05 14:32 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/Hash.java
> +                    values.set(pos, value);
Я это к тому, что мы сначала итерируемся по одному списку (это норм), но лишь для того, чтобы узнать индекс, и по этому индексу пойти в LinkedList (sic!). 
Нельзя ли обойтись одним списком из пар ключ-значений?

2020-12-05 14:33 UTC, dormidon requested changes
См. коммент.

2020-12-05 15:02 UTC, sdimosik commented on src/main/java/ru/mail/polis/ads/hash/Hash.java
> +                    values.set(pos, value);
Можно, просто, когда писал, не нашёл встроенных Pair

2020-12-09 09:01 UTC, dormidon approved these changes
Плюс-минус всё работает. 
В ведомость ставлю 5 баллов, скидывая 5 за бесстыдное заимствование.
Не надо такое практиковать - на старших курсах за такое заимствование мы отчисляем.

2020-12-09 09:02 UTC, closed without merging