HashTableOnChains | Roman Marasanov
polis-mail-ru/2020-ads pull request #236
Opened 2020-11-23 22:02 UTC by romanmarasanov

2020-11-23 22:11 UTC, romanmarasanov commented
По поводу красных тестов: компилятор пишет, что я использую какой-то ансейв (я понимаю, где он, т.к. его выделяет идея, но его природу я не понимаю). Поэтому идея запускает тесты с неким флагом -Xlint и все тесты проходят. Видимо, ваши тесты не такие умные :)
![1](https://user-images.githubusercontent.com/61559002/100021043-e0fd5880-2df1-11eb-88a5-d92082105158.png)
![2](https://user-images.githubusercontent.com/61559002/100021100-fd999080-2df1-11eb-938a-c8396aa10f30.png)

2020-11-28 14:54 UTC, dormidon commented
Проблема в том, что pull-request идет в ветку master, а не в ветку hash - поэтому CI видит вообще какой-то трэш.
![image](https://user-images.githubusercontent.com/727478/100518473-b8cf7a00-31a2-11eb-83f3-143f9e568247.png)
Нужно пересоздать PR в ветку `hash`, тогда, скорее всего, тесты в CI пройдут, да и PR будет содержать только нужные файлы (а не кучу предыдущих задач в нагрузку :)).

2020-11-28 14:55 UTC, dormidon requested changes
Пересоздать PR в ветку `hash`.

2020-11-28 15:15 UTC, romanmarasanov commented
Ок, тогда этот ПР закрываю

2020-11-28 15:15 UTC, closed without merging