Completed HW8
polis-mail-ru/2020-ads pull request #237
Opened 2020-11-23 22:49 UTC by FedorovDanila

2020-11-28 14:58 UTC, dormidon commented
Там тесты падают, ибо в классе с тестами нужно еще в одном месте добавить создание хеш-таблички.
![image](https://user-images.githubusercontent.com/727478/100518539-30050e00-31a3-11eb-9432-6ff111656896.png)

2020-11-28 14:58 UTC, dormidon requested changes
В тестах создавать таблицу еще в одном месте, чтобы все тесты завелись.

2020-11-30 16:42 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/MyHashTable.java
> +        return key.hashCode() % size;
А тут не может быть отрицательных значений?

2020-11-30 16:42 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/MyHashTable.java
> +        return key.hashCode() % size;
Плохие тесты, не ловят этот кейс :(

2020-11-30 16:42 UTC, dormidon requested changes
См. коммент.

2020-11-30 17:11 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/MyHashTable.java
> +        return Math.abs(key.hashCode() % size);
Ну ё-маё. И на лекции обсуждали и акцентировали, и в летучке было, что Math.abs нельзя использовать, ибо.
![image](https://user-images.githubusercontent.com/727478/100641195-32ed3380-3348-11eb-946d-e316464ea497.png)

2020-11-30 17:11 UTC, dormidon requested changes
См. коммент.

2020-11-30 17:19 UTC, FedorovDanila commented on src/main/java/ru/mail/polis/ads/hash/MyHashTable.java
> +        return Math.abs(key.hashCode() % size);
Так тут же и не может быть Integer.MIN_VALUE, так как модуль от результата деления, а не от хешкода

2020-11-30 17:19 UTC, FedorovDanila commented on src/main/java/ru/mail/polis/ads/hash/MyHashTable.java
> +        return Math.abs(key.hashCode() % size);
Разве нет?

2020-12-01 08:35 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/MyHashTable.java
> +        return Math.abs(key.hashCode() % size);
Аа, тут модуль от всего выражения. Сорри, стриггерился на модуль :)
Ну если size не будет превышать Integer.MAX_VALUE (а это максимальны размер массива в Java, так что кажется, что в нашей ситуации не будет), то результат `key.hashCode() % size` будет укладываться в `[-Integer.MAX_INT, Integer.MAX_INT]`, тогда мы не зацепим `Integer.MIN_VALUE` и с модулем все будет хорохо.

2020-12-01 08:35 UTC, dormidon approved these changes

2020-12-01 08:36 UTC, closed without merging