Пономарев Степан
polis-mail-ru/2020-ads pull request #238
Opened 2020-11-24 09:34 UTC by step-ponomarev

2020-11-28 15:00 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/HashTableImpl.java
> +public class HashTableImpl implements HashTable {
Нужно добавить параметры типа - Key и Value, а то жизнь на `Object` - это не true way.
Подробности про добавление параметров типа отписывал в чатике. 
Если вдруг останутся вопросы - стучитесь в личку.

2020-11-28 15:00 UTC, dormidon requested changes
Нужно добавить параметры типа - Key и Value, а то жизнь на `Object` - это не true way.
Подробности про добавление параметров типа отписывал в чатике. 
Если вдруг останутся вопросы - стучитесь в личку.

2020-11-30 16:01 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/ads/hash/HashTableImpl.java
> +public class HashTableImpl implements HashTable {
Сделал

2020-11-30 16:12 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/HashTableImpl.java
> +                bucket.add(i, node);
1. Таки мы в LinkedList добавляем по индексу - какая сложность?
2. Это добавление по индексу со сдвигом элементов, которые идут после. Оно ли нам надо?

2020-11-30 16:14 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/HashTableImpl.java
> +        bucket.remove(removedNode);
Сначала мы за линию пробежались, найдя нужный узел, затем за линию опять удаляем его?
Нельзя ли это за один просмотр списка сделать?

2020-11-30 16:15 UTC, dormidon requested changes
См. комменты.

2020-12-01 15:40 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/ads/hash/HashTableImpl.java
> +public class HashTableImpl implements HashTable {
поправил

2020-12-01 15:40 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/ads/hash/HashTableImpl.java
> +                bucket.add(i, node);
поправил

2020-12-05 14:40 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/HashTableImpl.java
> +        int i = hash % arraySize;
А здесь hash не может быть отрицательным?

2020-12-05 14:41 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/HashTableImpl.java
> +        this.buckets = new ArrayList<LinkedList<Node<K, V>>>(arraySize);
А для чего нам использовать ArrayList, если мы сами управляем размером массива, увеличивая его, когда надо? Мне кажется, если просто заменить на массив, то все станет проще.

2020-12-05 14:45 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/HashTableImpl.java
> +            if (bucket.get(i).getKey().equals(key)) {
Мы здесь в LinkedList в цикле берем элемент по индексу, каждое такое взятие - это O(n), а после того, как обнаружили индекс, делаем set по этому индексу, который тоже O(n). 
Т.е. мы сначала в связном списке нашли нужный узел, но запомнили его индекс, потом снова пошли по списку за линию, чтобы добраться до этого уже узла :) Это очень странно и не оптимально. 
Мне кажется, использование библиотечного LinkedList здесь ничего не упрощает. 
Если использовать самописную структурку для односвязного списка
```
class Node 
  Key key; 
  Value value;
  Node next;
```
то все будет работать оптимальнее и выглядеть проще.

2020-12-05 14:46 UTC, dormidon requested changes
См. комменты.

2020-12-06 12:52 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/HashTableImpl.java
> +                    node.key = key;
А зачем ключ переприсваивать, если он и так equals?

2020-12-06 12:57 UTC, dormidon approved these changes

2020-12-06 12:57 UTC, closed without merging