HomeWork8
polis-mail-ru/2020-ads pull request #239
Opened 2020-11-24 12:20 UTC by DaniilKornilov

2020-11-28 15:02 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/HashTableImpl.java
> +        ArrayList<Pair> pairs = array.get(hash(key.hashCode()) & (currentCapacity - 1));
`hash(key.hashCode()) & (currentCapacity - 1)` - получение индекса встречатся много раз - нужно вынести в функцию.

2020-11-28 15:02 UTC, dormidon requested changes
1. `hash(key.hashCode()) & (currentCapacity - 1)` - вынести в функцию
2. Потянуть upstream - в нем появились новые тесты.

2020-12-05 14:47 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/HashTableImpl.java
> +    private ArrayList<Pair> bucketArray;
А нужен ли нам тут ArrayList, если мы сами управляем размером массива.
Не будет ли проще использовать обычный массив?

2020-12-05 14:48 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/HashTableImpl.java
> +            bucketArray = new ArrayList<>();
Тут ведь мы знаем размер нового массива, можно сразу его и создать.
В текущем виде у нас ArrayList будет еще кучу раз увеличиваться в размерах по мере добавления в него элементов.

2020-12-05 14:51 UTC, dormidon commented on src/test/java/ru/mail/polis/ads/hash/HashTableBaseTest.java
> -        table.put(new String("1"), "testStringValue3");
А это зачем?
Тест специально делает newString(строковый литерал), чтобы избежать ситуации, что строковые литералы имеют одинаковый identityHashCode.
![image](https://user-images.githubusercontent.com/727478/101246137-6b16bc80-3722-11eb-9349-698cad699c06.png)

Надо откатить эти изменения в тесте.

2020-12-05 14:51 UTC, dormidon requested changes
См. комменты.

2020-12-05 22:28 UTC, DaniilKornilov commented on src/test/java/ru/mail/polis/ads/hash/HashTableBaseTest.java
> -        table.put(new String("1"), "testStringValue3");
Понял, не обратил внимания, что idea так отформатировала при коммите

2020-12-09 09:03 UTC, dormidon approved these changes

2020-12-09 09:04 UTC, closed without merging