Hash task
polis-mail-ru/2020-ads pull request #241
Opened 2020-11-24 16:25 UTC by cheeju69

6/6 test

2020-11-28 15:07 UTC, dormidon requested changes
![image](https://user-images.githubusercontent.com/727478/100518748-92124300-31a4-11eb-8896-e6ebf7cc7460.png)
Нет исходников - нужно докинуть.

2020-12-05 14:56 UTC, dormidon commented
Стоит ждать исходников? :)

2020-12-05 15:05 UTC, cheeju69 commented
Да, у меня потерялось сообщение и я забыла ,постараюсь скинуть в ближайшее
время

сб, 5 дек. 2020 г., 17:56 Dmitry Schitinin <notifications@github.com>:

> Стоит ждать исходников? :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/polis-mail-ru/2020-ads/pull/241#issuecomment-739263554>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIVPDYBUD4KM4ACZNILHMDDSTJCZJANCNFSM4UBDQO4Q>
> .
>

2020-12-09 09:07 UTC, dormidon commented
![image](https://user-images.githubusercontent.com/727478/101608659-0c4d8d80-3a17-11eb-8e06-5d963b8e2cd1.png)

2020-12-28 09:41 UTC, dormidon commented
Ждун не дождался.

2020-12-28 09:41 UTC, closed without merging