Add HashTable Peutina Veronika
polis-mail-ru/2020-ads pull request #243
Opened 2020-11-25 02:01 UTC by NickPeut

2020-11-28 15:09 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/HashTableRealize.java
> +        if (size + 2 >= capacity)
А отчего такой выбор условия ресайза? Почему +2?

2020-11-28 15:11 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/HashTable.java
> +public interface HashTable<Key, Value> {
Нужно откатить изменения в этом классе (разрешить конфликт), чтобы система CI смогла подхватить PR и прогнать тесты.

2020-11-28 15:12 UTC, dormidon requested changes
Коммент про ресайз + порешать конфликты.
![image](https://user-images.githubusercontent.com/727478/100518843-414f1a00-31a5-11eb-803f-7435a084688a.png)

2020-12-01 14:50 UTC, NickPeut commented on src/main/java/ru/mail/polis/ads/hash/HashTable.java
> +public interface HashTable<Key, Value> {
я создавала полностью от руки файлы, я не понимаю, как к форкнутому проекту подцепить эту ветку из основного

2020-12-05 14:55 UTC, dormidon commented
Вижу, что PR нормальный получился.
Теперь еще в тестах нужно начать создавать инстанс вашей реализации таблицы, чтобы тесты прошли.
На текущий момент все падает NPE 
![image](https://user-images.githubusercontent.com/727478/101246188-cb0d6300-3722-11eb-93bc-77642d54c8a9.png)

Нужно в тесте вот тут возвращать инстансы:
![image](https://user-images.githubusercontent.com/727478/101246227-0b6ce100-3723-11eb-9a17-ead9d2bdd6de.png)

2020-12-05 14:55 UTC, dormidon requested changes
Довести тесты до рабочего состояния.

2020-12-09 09:06 UTC, dormidon commented
Тесты завелись, но не все проходят. 
Где-то возникает NPE
![image](https://user-images.githubusercontent.com/727478/101608562-e7f1b100-3a16-11eb-9acd-ebe12387b540.png)
Нужно дочинить.

2020-12-09 09:06 UTC, dormidon requested changes
Дожать тесты.

2020-12-13 17:45 UTC, dormidon approved these changes

2020-12-13 17:45 UTC, closed without merging