HashTableOnChains | Marasanov
polis-mail-ru/2020-ads pull request #246
Opened 2020-11-28 15:41 UTC by romanmarasanov

2020-11-28 15:47 UTC, romanmarasanov commented
У меня какие-то беды с гитом :(
Не могу нормально откоммитить так, чтобы измененные файлы содержали только новый класс и маленькое изменение в тестовом файле

2020-12-05 14:58 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/HashTableOnChains.java
> +            res = res.next;
Если тесты проходят, то это плохие тесты и моя недоработка.
В данном случае мы вообще не сравниваем ключи на equals, а просто берем последний элемент цепочки.
Очевидно, что это не корректное поведение.

2020-12-05 14:59 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/HashTableOnChains.java
> +        while (res.key != k && res.next != null){
Вот тут тесты не должны проходить - специально добавлял кейсы, чтобы != и == не работали, а работал только equals. 
Если тесты проходят, то опять же плохие тесты и моя недоработка.

2020-12-05 15:00 UTC, dormidon commented on src/main/java/ru/mail/polis/ads/hash/HashTableOnChains.java
> +        while (!res.next.key.equals(k)) res = res.next;
Тут вообще должен NPE лететь, когда мы дойдем до конца цепочки.

2020-12-05 15:01 UTC, dormidon commented on src/test/java/ru/mail/polis/ads/hash/HashTableBaseTest.java
> +        return new HashTableOnChains<>();
Там если подтянуть upstream, то появится еще один метод в тесте, где нужно возвращать инстанс таблички.

2020-12-05 15:05 UTC, dormidon commented
Чтобы получить хороший PR, проще всего:
1. Переключиться на master в вашем репозитории (`git checkout master`)
2. От мастера создать новую ветку (`git checkout -b hash_2`)
3. В эту ветку подтянуть ветку `hash` центрального репозитория (https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/syncing-a-fork)
4. Из текущий вашей ветки в новую перенести вашу реализацию
5. Поправить тестовый класс - в двух местах возвращать вашу реализацию таблички
![image](https://user-images.githubusercontent.com/727478/101246441-67843500-3724-11eb-86d2-01f12a2a367c.png)
6. Закоммитить-запушить-создать новый PR из вашей новой ветки в центральный репозиторий в ветку `hash`

2020-12-05 15:06 UTC, dormidon requested changes
1. Создать правильный PR
2. При этом подхватятся новые тесты, часть из которых, скорее всего, сломается.
3. Исправить ошибки и замечания.

2020-12-07 12:19 UTC, romanmarasanov commented
Хорошо, закрываю этот ПР

2020-12-07 12:19 UTC, closed without merging