Hw9 | Sachuk Ilya
polis-mail-ru/2020-ads pull request #255
Opened 2020-12-08 16:57 UTC by IlyaAAAA

2020-12-13 17:58 UTC, dormidon commented
Код подозрительно похож на #254.
И наша искалка дубликатов зашкаливает:
![image](https://user-images.githubusercontent.com/727478/102019689-f37e0880-3d85-11eb-8862-e4b735ecf0d6.png)

Как это можно объяснить?

2020-12-13 17:59 UTC, dormidon requested changes
Невероятно похоже на #254 .

2020-12-13 18:09 UTC, step-ponomarev commented
> Код подозрительно похож на #254.
> И наша искалка дубликатов зашкаливает:
> ![image](https://user-images.githubusercontent.com/727478/102019689-f37e0880-3d85-11eb-8862-e4b735ecf0d6.png)
> 
> Как это можно объяснить?

Да, мы обычно делаем алгоритмы в двоем, сидим в дискорде и разбираем.

2020-12-13 19:13 UTC, dormidon commented
Так тогда все баллы надо на двоих поделить? :)

2020-12-13 19:13 UTC, dormidon commented
Ладно обсудить идею, моменты тонкие. Но это просто один и тот же код.

2020-12-24 16:50 UTC, IlyaAAAA commented
Так как решали вместе, то получился очень похожий код, но мы не просто брали и копировали друг у друга, а разбирали задания. Оно оказалось не очень простым. Такого больше не повторится

2020-12-28 09:47 UTC, dormidon commented
В ведомость 8 баллов.

2020-12-28 09:47 UTC, closed without merging