Implemented HW 9
polis-mail-ru/2020-ads pull request #263
Opened 2020-12-09 22:33 UTC by kish-dev

1 - https://www.e-olymp.com/ru/submissions/7998380
2 - https://www.e-olymp.com/ru/submissions/7998821
3 - https://www.e-olymp.com/ru/submissions/7998688

2020-12-13 18:52 UTC, dormidon commented
Код подозрительно схож  #251.
И наша система поиска дубликатов подтверждает это.
![image](https://user-images.githubusercontent.com/727478/102020924-6179fe00-3d8d-11eb-9087-4fb8f4965778.png)

Что на это скажете?

2020-12-13 18:53 UTC, dormidon commented
Выглядит, что MainTwo - решение Даниила, только `used` переименован в `visited`.

2020-12-13 18:53 UTC, dormidon requested changes
См. комменты.

2020-12-13 20:15 UTC, kish-dev commented
> Выглядит, что MainTwo - решение Даниила, только `used` переименован в `visited`.

Каюсь, я взял, после того, как моё решение не проходило все тесты.

2020-12-14 07:49 UTC, dormidon commented
Ок. Тогда за эту задачу 1 балл, в ведомость пока 5 баллов. 
Ждем остальных задач.

2020-12-14 07:50 UTC, dormidon commented
Хотя там на итоговую 5 уже набрано (во многом благодаря летучкам).
Поэтому дорешивать эту и другую домашку можете по своему желанию.

2020-12-14 07:51 UTC, dormidon approved these changes

2020-12-14 10:47 UTC, kish-dev commented
> Хотя там на итоговую 5 уже набрано (во многом благодаря летучкам).
> Поэтому дорешивать эту и другую домашку можете по своему желанию.

Во многом, благодаря пропущенным летучкам, я 5 не набрал до 9 задания(

2020-12-28 09:50 UTC, closed without merging