Work 2, Saveliy Schur
polis-mail-ru/2020-ads pull request #53
Opened 2020-10-07 22:05 UTC by SaveliyShur

1) https://www.e-olymp.com/ru/submissions/7468825
2) https://www.e-olymp.com/ru/submissions/7441623
3) https://www.e-olymp.com/ru/submissions/7442162
4) https://www.e-olymp.com/ru/submissions/7460821
5) https://www.e-olymp.com/ru/problems/4037

2020-10-09 09:01 UTC, dormidon commented
На одну задачу нет сабмишена.
Попробовал сам ее засабмитить, получил 
![image](https://user-images.githubusercontent.com/727478/95564215-2672eb80-0a27-11eb-9937-f2f1dcfdb497.png)

2020-10-09 09:02 UTC, dormidon requested changes
Нужен сабмишен задачки.

2020-10-09 13:01 UTC, SaveliyShur commented
Да сейчас скину, нечаянно не ту ссылку добавил. Чтобы проходили задачки нужно имя класса на Main менять, так система проверки устроена)

2020-10-09 13:03 UTC, SaveliyShur commented
Обновил комментарий

2020-10-09 13:05 UTC, dormidon commented
А почему у меня не работает, когда я код сабмичу сам? Что мне нужно поменять?

2020-10-09 21:50 UTC, SaveliyShur commented
> А почему у меня не работает, когда я код сабмичу сам? Что мне нужно поменять?

Нужно переименовывать класс и Создание объекта этого класса на Main, так как у них файл я так понимаю называется Main

2020-10-11 14:59 UTC, dormidon approved these changes

2020-10-11 14:59 UTC, closed without merging