hw2
polis-mail-ru/2020-ads pull request #55
Opened 2020-10-09 01:17 UTC by sdimosik

1) https://www.e-olymp.com/ru/submissions/7474732
2) https://www.e-olymp.com/ru/submissions/7474840
3) https://www.e-olymp.com/ru/submissions/7474946
4) https://www.e-olymp.com/ru/submissions/7475731
5) https://www.e-olymp.com/ru/submissions/7475794

2020-10-09 09:04 UTC, dormidon commented
Так а сами решения где? :)
![image](https://user-images.githubusercontent.com/727478/95564531-a13c0680-0a27-11eb-974a-e3d3a559a8c9.png)

2020-10-09 09:05 UTC, dormidon requested changes
Нужно пушнуть решения.

2020-10-09 16:33 UTC, sdimosik commented
@dormidon исправил)

2020-10-11 15:00 UTC, dormidon approved these changes

2020-10-11 15:00 UTC, closed without merging